yo_vendo_main_homepage:
    path:     /hello/{name}
    defaults: { _controller: YoVendoMainBundle:Default:index }


yo_vendo_view_dashboard:
    path:     /view/dashboard
    defaults: { _controller: YoVendoMainBundle:Default:viewDashBoard }

yo_vendo_view_dashboard_date:
    path:     /view/dashboard/{startDate}/{endDate}
    defaults: { _controller: YoVendoMainBundle:Default:viewDashBoard }
